name: EPG Guncelle

on:
  schedule:
    - cron: '0 3 * * *' # Her gece 03:00'te çalışır
  workflow_dispatch: # Manuel çalıştırma butonu ekler

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri Yukle
        run: |
          pip install requests beautifulsoup4

      - name: Scripti Calistir
        env:
          GH_TOKEN: ${{ secrets.EPG_TOKEN }}
        run: python epg_yayin.py

